# -*- coding: utf-8 -*-
"""Customer Churn Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1evzUxrqfBIvGOs6aRyfq3UtzsbXEBB17

**Mount Drive & Import Libraries**
"""

from google.colab import drive
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Mount Google Drive
drive.mount('/content/drive')

# Load dataset (update path if needed)
file_path = "/content/drive/MyDrive/datasetnws/Telco-Customer-Churn/train.csv"
df = pd.read_csv(file_path)

# Check first rows
df.head()

"""**Data Overview**"""

# Shape of dataset
print("Rows:", df.shape[0], " | Columns:", df.shape[1])

# Info & missing values
df.info()
df.isnull().sum()

# Churn rate
df['Churn'].value_counts(normalize=True) * 100

# ----- DATA CLEANING -----

# 1. Check missing values
print("Missing values per column:\n", df.isnull().sum())

# 2. Handle missing values in 'Churn Category', 'Churn Reason', 'Offer', 'Internet Type'
#    -> Fill NaN with "Unknown"
for col in ['Churn Category','Churn Reason','Offer','Internet Type']:
    df[col] = df[col].fillna("Unknown")

# 3. Convert categorical columns with Yes/No to integers (if needed)
# Example: Paperless Billing (Yes=1, No=0)
df['Paperless Billing'] = df['Paperless Billing'].map({'Yes':1,'No':0})

# 4. Ensure numeric columns are correct
numeric_cols = ['Total Charges','Monthly Charge','Total Revenue']
df[numeric_cols] = df[numeric_cols].apply(pd.to_numeric, errors='coerce')

# Fill any numeric NaN with median
df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].median())

# 5. Drop duplicates (if any)
df = df.drop_duplicates()

# Final check
print("Dataset shape after cleaning:", df.shape)
df.head()

"""**Basic Churn Distribution**"""

plt.figure(figsize=(6,6))
df['Churn'].value_counts().plot(
    kind='bar',
    color=['skyblue','salmon']
)
plt.title("Churn Distribution (0=Stayed, 1=Churned)")
plt.xlabel("Churn")
plt.ylabel("Count")
plt.show()

"""**Churn by Contract Type**"""

contract_churn = df.groupby("Contract")['Churn'].mean()

plt.figure(figsize=(8,6))
contract_churn.plot(kind='bar', color="teal")
plt.title("Churn Rate by Contract Type")
plt.ylabel("Churn Rate")
plt.xlabel("Contract Type")
plt.show()

"""**Tenure vs Churn**"""

plt.figure(figsize=(8,6))
sns.histplot(data=df, x="Tenure in Months", hue="Churn", bins=30, kde=False, palette=["skyblue","salmon"])
plt.title("Tenure vs Churn")
plt.xlabel("Tenure (Months)")
plt.ylabel("Customers")
plt.show()

"""**Monthly Charges vs Churn**"""

plt.figure(figsize=(8,6))
sns.histplot(data=df, x="Monthly Charge", hue="Churn", bins=30, kde=False, palette=["skyblue","salmon"])
plt.title("Monthly Charges vs Churn")
plt.xlabel("Monthly Charge")
plt.ylabel("Customers")
plt.show()

"""**Cross Analysis**"""

sns.countplot(data=df, x="Gender", hue="Churn", palette=["skyblue","salmon"])
plt.title("Churn by Gender")
plt.show()

#Internet Type

sns.countplot(data=df, x="Internet Type", hue="Churn", palette=["skyblue","salmon"])
plt.title("Churn by Internet Type")
plt.xticks(rotation=30)
plt.show()

"""**Payment Method**"""

sns.countplot(data=df, x="Payment Method", hue="Churn", palette=["skyblue","salmon"])
plt.title("Churn by Payment Method")
plt.xticks(rotation=30)
plt.show()

"""**Senior Citizens**"""

sns.countplot(data=df, x="Senior Citizen", hue="Churn", palette=["skyblue","salmon"])
plt.title("Churn by Senior Citizen (0=No, 1=Yes)")
plt.show()

"""**Paperless Billing**"""

sns.countplot(data=df, x="Paperless Billing", hue="Churn", palette=["skyblue","salmon"])
plt.title("Churn by Paperless Billing")
plt.show()

"""**Correlation Heatmap**"""

plt.figure(figsize=(12,8))
sns.heatmap(df.corr(numeric_only=True), annot=False, cmap="coolwarm", linewidths=0.5)
plt.title("Correlation Heatmap")
plt.show()

"""###  Key Insights from Churn Analysis

1. **Overall Churn Rate**: ~26.5% (about 1 in 4 customers leave).  
2. **Contract Type**: Month-to-Month contracts have the highest churn.  
3. **Tenure**: Customers within first year are most likely to churn. Long-tenured customers are loyal.  
4. **Monthly Charges**: Higher monthly charges strongly linked to churn.  
5. **Internet Type**: Fiber optic customers churn more than DSL.  
6. **Payment Method**: Electronic check users churn more than auto-pay/credit card users.  
7. **Paperless Billing**: More churn compared to paper billing.  
8. **Senior Citizens**: Slightly higher churn rate.  
9. **Streaming Services**: Streaming TV & movie users churn more.  

📌 **Conclusion**: Customer drop-off is led by short contracts, high monthly charges, and billing/payment methods. Retention can be improved with loyalty programs, discounts for long-term contracts, and better engagement with at-risk segments.

"""